<a href="https://colab.research.google.com/github/cupoglee/Simple-Java/blob/main/GoogleColabBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

System specifications.

In [ ]:
!cat /proc/cpuinfo

processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 79
model name	: Intel(R) Xeon(R) CPU @ 2.20GHz
stepping	: 0
microcode	: 0xffffffff
cpu MHz		: 2200.158
cache size	: 56320 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt arat md_clear arch_capabilities
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa mmio_stale_data retbleed
bogomips	: 4400.31
clflush size	: 64
cache_alignment	: 64
addres

In [ ]:
!cat /proc/meminfo

MemTotal:       13294252 kB
MemFree:         9524896 kB
MemAvailable:   12379592 kB
Buffers:           62608 kB
Cached:          2983456 kB
SwapCached:            0 kB
Active:           853680 kB
Inactive:        2674200 kB
Active(anon):       1124 kB
Inactive(anon):   482080 kB
Active(file):     852556 kB
Inactive(file):  2192120 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:               392 kB
Writeback:             0 kB
AnonPages:        480564 kB
Mapped:           289040 kB
Shmem:              1388 kB
KReclaimable:     101952 kB
Slab:             137832 kB
SReclaimable:     101952 kB
SUnreclaim:        35880 kB
KernelStack:        4144 kB
PageTables:         8700 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     6647124 kB
Committed_AS:    1985012 kB
VmallocTotal:   34359738367 kB
VmallocUsed:        9092 kB
VmallocChunk:          0 kB
Percpu:          

Getting started with python.


In [7]:
# Numpy
import numpy as np
one_dimensional_array = np.array([5, 6, 7])
print(one_dimensional_array)
two_dimensional_array = np.array([[5, 6], [7, 8]])
print(two_dimensional_array)

# arranging in ascending order
order = np.arange(5, 12)
print(order)

# Using random.randint to print random numbers between two given numbers of given size
numbers_between_30_and_40 = np.random.randint(high = 40, low = 30, size = 4)
print(numbers_between_30_and_40)

#

[5 6 7]
[[5 6]
 [7 8]]
[ 5  6  7  8  9 10 11]
[36 33 34 30]
